---
# install_and_configure_keepalived/handlers/main.yml

- name: 'Restart the keepalived service'
  ansible.builtin.service:
    name: "{{ systemd_unit_name }}"
    state: 'restarted'

- name: 'Reload of the keepalived configuration'
  ansible.builtin.service:
    name: "{{ systemd_unit_name }}"
    state: 'reloaded'
